<a href="https://colab.research.google.com/github/aswinss949/ICT-BATCH-9/blob/main/case_study.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##1: Load SpaceX Launch Data from API

In [29]:
import requests
import pandas as pd

# API endpoint for SpaceX lau
LAUNCHES_API_URL = "https://api.spacexdata.com/v4/launches"

# Fetch data from the API
response = requests.get(LAUNCHES_API_URL)
launches_data = response.json()

launches_df = pd.DataFrame(launches_data)[['name', 'date_utc', 'success', 'details', 'rocket']]

launches_df['date_utc'] = pd.to_datetime(launches_df['date_utc'])
launches_df['launch_year'] = launches_df['date_utc'].dt.year

display(launches_df.head())
display(launches_df.info())

,name,date_utc,success,details,rocket,launch_year
0,FalconSat,2006-03-24 22:30:00+00:00,False,Engine failure at 33 seconds and loss of vehicle,5e9d0d95eda69955f709d1eb,2006
1,DemoSat,2007-03-21 01:10:00+00:00,False,Successful first stage burn and transition to ...,5e9d0d95eda69955f709d1eb,2007
2,Trailblazer,2008-08-03 03:34:00+00:00,False,Residual stage 1 thrust led to collision betwe...,5e9d0d95eda69955f709d1eb,2008
3,RatSat,2008-09-28 23:15:00+00:00,True,Ratsat was carried to orbit on the first succe...,5e9d0d95eda69955f709d1eb,2008
4,RazakSat,2009-07-13 03:35:00+00:00,True,None,5e9d0d95eda69955f709d1eb,2009

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         205 non-null    object
 1   date_utc     205 non-null    datetime64[ns, UTC]
 2   success      186 non-null    object
 3   details      134 non-null    object
 4   rocket       205 non-null    object
 5   launch_year  205 non-null    int32
dtypes: datetime64[ns, UTC](1), int32(1), object(4)
memory usage: 8.9+ KB

None

## Step 2: Load SpaceX Rocket Data from API

Load Launch Data

In [30]:
import requests
import pandas as pd

# Fetch launch data
launch_url = "https://api.spacexdata.com/v4/launches"
launch_data = requests.get(launch_url).json()

# Convert to DataFrame
launch_df = pd.DataFrame(launch_data)

# Select required columns
launch_df = launch_df[['name', 'date_utc', 'success', 'details', 'rocket']]

# Convert date and extract year
launch_df['date_utc'] = pd.to_datetime(launch_df['date_utc'])
launch_df['year'] = launch_df['date_utc'].dt.year

launch_df.head()

,name,date_utc,success,details,rocket,year
0,FalconSat,2006-03-24 22:30:00+00:00,False,Engine failure at 33 seconds and loss of vehicle,5e9d0d95eda69955f709d1eb,2006
1,DemoSat,2007-03-21 01:10:00+00:00,False,Successful first stage burn and transition to ...,5e9d0d95eda69955f709d1eb,2007
2,Trailblazer,2008-08-03 03:34:00+00:00,False,Residual stage 1 thrust led to collision betwe...,5e9d0d95eda69955f709d1eb,2008
3,RatSat,2008-09-28 23:15:00+00:00,True,Ratsat was carried to orbit on the first succe...,5e9d0d95eda69955f709d1eb,2008
4,RazakSat,2009-07-13 03:35:00+00:00,True,None,5e9d0d95eda69955f709d1eb,2009

Load Rocket Metadata

In [31]:
rocket_url = "https://api.spacexdata.com/v4/rockets"
rocket_data = requests.get(rocket_url).json()

rocket_df = pd.DataFrame(rocket_data)

rocket_df = rocket_df[['id', 'name', 'type', 'active', 'stages']]

rocket_df.head()

                         id          name    type  active  stages
0  5e9d0d95eda69955f709d1eb      Falcon 1  rocket   False       2
1  5e9d0d95eda69973a809d1ec      Falcon 9  rocket    True       2
2  5e9d0d95eda69974db09d1ed  Falcon Heavy  rocket    True       2
3  5e9d0d96eda699382d09d1ee      Starship  rocket   False       2

 Merge Data

In [32]:
merged_df = launch_df.merge(rocket_df, left_on='rocket', right_on='id', how='left')

merged_df.head()

,name_x,date_utc,success,details,rocket,year,id,name_y,type,active,stages
0,FalconSat,2006-03-24 22:30:00+00:00,False,Engine failure at 33 seconds and loss of vehicle,5e9d0d95eda69955f709d1eb,2006,5e9d0d95eda69955f709d1eb,Falcon 1,rocket,False,2
1,DemoSat,2007-03-21 01:10:00+00:00,False,Successful first stage burn and transition to ...,5e9d0d95eda69955f709d1eb,2007,5e9d0d95eda69955f709d1eb,Falcon 1,rocket,False,2
2,Trailblazer,2008-08-03 03:34:00+00:00,False,Residual stage 1 thrust led to collision betwe...,5e9d0d95eda69955f709d1eb,2008,5e9d0d95eda69955f709d1eb,Falcon 1,rocket,False,2
3,RatSat,2008-09-28 23:15:00+00:00,True,Ratsat was carried to orbit on the first succe...,5e9d0d95eda69955f709d1eb,2008,5e9d0d95eda69955f709d1eb,Falcon 1,rocket,False,2
4,RazakSat,2009-07-13 03:35:00+00:00,True,None,5e9d0d95eda69955f709d1eb,2009,5e9d0d95eda69955f709d1eb,Falcon 1,rocket,False,2

Add Simulated Country

In [33]:
import numpy as np

countries = ['USA', 'Russia', 'India', 'China', 'France']
merged_df['country'] = np.random.choice(countries, size=len(merged_df))

merged_df.head()

,name_x,date_utc,success,details,rocket,year,id,name_y,type,active,stages,country
0,FalconSat,2006-03-24 22:30:00+00:00,False,Engine failure at 33 seconds and loss of vehicle,5e9d0d95eda69955f709d1eb,2006,5e9d0d95eda69955f709d1eb,Falcon 1,rocket,False,2,France
1,DemoSat,2007-03-21 01:10:00+00:00,False,Successful first stage burn and transition to ...,5e9d0d95eda69955f709d1eb,2007,5e9d0d95eda69955f709d1eb,Falcon 1,rocket,False,2,India
2,Trailblazer,2008-08-03 03:34:00+00:00,False,Residual stage 1 thrust led to collision betwe...,5e9d0d95eda69955f709d1eb,2008,5e9d0d95eda69955f709d1eb,Falcon 1,rocket,False,2,China
3,RatSat,2008-09-28 23:15:00+00:00,True,Ratsat was carried to orbit on the first succe...,5e9d0d95eda69955f709d1eb,2008,5e9d0d95eda69955f709d1eb,Falcon 1,rocket,False,2,Russia
4,RazakSat,2009-07-13 03:35:00+00:00,True,None,5e9d0d95eda69955f709d1eb,2009,5e9d0d95eda69955f709d1eb,Falcon 1,rocket,False,2,USA

Store in SQLite

In [34]:
import sqlite3

conn = sqlite3.connect("spacex_launches.db")

merged_df.to_sql("launches", conn, if_exists="replace", index=False)

print("Data stored successfully!")

Data stored successfully!

SQL Analysis Queries

In [35]:

query1 = """
SELECT country, COUNT(*) as total_launches
FROM launches
GROUP BY country
ORDER BY total_launches DESC;
"""

pd.read_sql_query(query1, conn)

  country  total_launches
0   China              49
1  France              44
2   India              42
3     USA              35
4  Russia              35

In [36]:
query2 = """
SELECT year, COUNT(*) as total_launches
FROM launches
GROUP BY year
ORDER BY total_launches DESC
LIMIT 1;
"""

pd.read_sql_query(query2, conn)

   year  total_launches
0  2022              62

In [37]:
query3 = """
SELECT name_x, COUNT(*) as launch_count
FROM launches
GROUP BY name_x
ORDER BY launch_count DESC
LIMIT 5;
"""

pd.read_sql_query(query3, conn)

                      name_x  launch_count
0  ispace Mission 1 & Rashid             1
1                       ZUMA             1
2     WorldView Legion 1 & 2             1
3        Viasat-3 & Arcturus             1
4                    USSF-44             1